console.log(1234)
throw(new Error(0))